### ISSUE TITLE
TypeError: Object.defineProperty called on non-object

### ISSUE THREAD

**Issue by nicholashead** [twilio/twilio-taskrouter.js#43]
This error seems to happen occasionally. Here's the Sentry info:

https://sentry.io/share/issue/1a50917f3599473b9abfbfc4a4451d1b/

```
TypeError: Object.defineProperty called on non-object
  at Function.defineProperty(<anonymous>)
  at Object.setProperties(/js/taskrouter/v1.21/taskrouter.min.js:2:20376)
  at Object.createEntity(/js/taskrouter/v1.21/taskrouter.min.js:2:13709)
  at WorkerClient._emitMessage(/js/taskrouter/v1.21/taskrouter.min.js:1:17529)
  at WebSocket.ws.onmessage(/js/taskrouter/v1.21/taskrouter.min.js:1:6896)
```

**Comment by AndreyTwilio** [comment]
Hello @nicholashead 
This error seems to be relevant to our first version of TR SDK. Closing this issue as hopefully it has been fixed. Please reopen the issue here, if a newer version of SDK v1 has the same problem, and consider updating to the SDK version stored in this repository.
